import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Poppins } from "next/font/google";
import "./globals.css";
import Image from "next/image";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["300", "500"],
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.className} antialiased`}>
        <nav className="h-32 bg-stone-950">
          <div className="flex justify-between items-center h-full px-8">
            {/* Left Section - Centered and Pinned */}
            <div>
              <ul className="flex flex-row gap-6 text-white text-2xl">
                <li>HOME</li>
                <li>ABOUT</li>
                <li>OUR STORY</li>
                <li>CONTACT</li>
              </ul>
            </div>

            {/* Right Section - Pinned */}
            <div>
              <Image
                className=""
                src="/greyscalelogo.png"
                alt="KDCU Logo"
                width={109}
                height={109}
                priority
              />
            </div>
          </div>
        </nav>

        {children}
        <footer className="bg-stone-950 text-white py-10">
          <div className="container mx-auto grid grid-cols-1 md:grid-cols-3 gap-8">
            {/* Column 1 - Takes as much space as possible */}
            <div className="flex flex-col items-center md:items-start text-center md:text-left flex-grow">
              <Image
                src="/greyscalelogo.png" // Replace with your logo path
                alt="Footer Logo"
                width={100}
                height={100}
                className="mb-4 mx-auto"
              />
              <p className="text-sm">
                IN COLLABORATION WITH SANDBOX SWAPMEET AND LICENSE PARTNER PRIME
                STAGE DXB
              </p>
            </div>

            {/* Column 2 - Takes minimum space */}
            <div className="flex flex-col items-center md:items-start text-center md:text-left">
              <h4 className="text-lg font-bold mb-4">INFORMATION</h4>
              <ul className="space-y-2 font-light">
                <li>
                  <a href="#" className="text-white hover:underline">
                    HOME
                  </a>
                </li>
                <li>
                  <a href="#" className="text-white hover:underline">
                    ABOUT
                  </a>
                </li>
                <li>
                  <a href="#" className="text-white hover:underline">
                    OUR STORY
                  </a>
                </li>
                <li>
                  <a href="#" className="text-white hover:underline">
                    CONTACT
                  </a>
                </li>
              </ul>
            </div>

            {/* Column 3 - Takes minimum space */}
            <div className="flex flex-col items-center md:items-start text-center md:text-left">
              <h4 className="text-lg font-bold mb-4">CONNECT WITH US</h4>
              <ul className="space-y-2 font-light">
                <li>
                  <a
                    href="https://www.instagram.com/thepixiesdance/"
                    target="_blank"
                    rel="noopener noreferrer"
                    className="text-white hover:underline"
                  >
                    INSTAGRAM
                  </a>
                </li>
                <li>
                  <a
                    href="https://www.youtube.com/@THEPIXIESDANCE"
                    target="_blank"
                    rel="noopener noreferrer"
                    className="text-white hover:underline"
                  >
                    YOUTUBE
                  </a>
                </li>
                <li>
                  <a
                    href="https://primestagedxb.com/"
                    target="_blank"
                    rel="noopener noreferrer"
                    className="text-white hover:underline"
                  >
                    PRIMESTAGE DXB
                  </a>
                </li>
                <li>
                  <a
                    href="https://www.instagram.com/sandboxswapmeet/"
                    target="_blank"
                    rel="noopener noreferrer"
                    className="text-white hover:underline"
                  >
                    SANDBOX SWAPMEET
                  </a>
                </li>
              </ul>
            </div>
          </div>
        </footer>
      </body>
    </html>
  );
}
